### ISSUE TITLE
Support for php 7.3+

### ISSUE THREAD

**Issue by dogawaf** [connecta-ag/t3footnotes#1]
Hi 

Would you min to raise the php compatibility to php 7.3+?

**Comment by jochenrieger** [comment]
Salut Daniel,

thanks for raising the issue. I will try to talk care of that asap and get back to you here. 

Kind regards
Jochen

**Comment by jochenrieger** [comment]
@dogawaf 

Hi Daniel,

I raised the PHP version in the composer file. I did some basic testing – all looked fine with 7.3 + 7.4.

Let me know if you have any further issues...

Cheers
Jochen

**Comment by dogawaf** [comment]
Hi @jochenrieger 

Thx for that!
I will update the projects that use t3footnotes and will get batck here if I encounter any trouble.

And also, thx for sharing this extension to the TYPO3 community.
It is very useful for editors.

**Comment by jochenrieger** [comment]
@dogawaf Thank you for the nice feedback, Daniel. I'm happy the extension can be of use.

Let me know if you have any wishes, suggestions or of course, in case you encounter any issues. I'm also planning to test it using T3 v10 some time the next couple of days and push another release marking it as compatible.
